// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v5.27.1
// source: packages/proto/src/auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "auth";

export interface PostLoginDTO {
  username: string;
  password: string;
}

export interface ResponseLoginDTO {
  id: number;
  username: string;
  role: string;
}

export interface PostRtHashDTO {
  username: string;
  hashedRT: string;
}

export interface GetRtHashDTO {
  username: string;
}

export interface ResponseRtHashDTO {
  hashedRT: string;
}

export interface Empty {
}

export const AUTH_PACKAGE_NAME = "auth";

export interface AuthServiceClient {
  postLogin(request: PostLoginDTO): Observable<ResponseLoginDTO>;

  postRtHash(request: PostRtHashDTO): Observable<Empty>;

  getRtHash(request: GetRtHashDTO): Observable<ResponseRtHashDTO>;
}

export interface AuthServiceController {
  postLogin(request: PostLoginDTO): Promise<ResponseLoginDTO> | Observable<ResponseLoginDTO> | ResponseLoginDTO;

  postRtHash(request: PostRtHashDTO): Promise<Empty> | Observable<Empty> | Empty;

  getRtHash(request: GetRtHashDTO): Promise<ResponseRtHashDTO> | Observable<ResponseRtHashDTO> | ResponseRtHashDTO;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["postLogin", "postRtHash", "getRtHash"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
